apiVersion: v1
kind: Service
metadata:
  name: control-plane-app
  namespace: platform-apps
  labels:
    app.kubernetes.io/name: control-plane-app
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: control-plane-app
  ports:
    - name: http
      port: 8083
      targetPort: http
